project:
  type: website
  output-dir: docs

website:
  title: "Mila Matich"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - favs.qmd
      - abroad.qmd
      - resume.qmd

format:
  html:
    theme:
      - morph
      - brand
    css: styles.css
    toc: true
    page-layout: full



