---
title: "About Me"
---

Hey! If you want to learn a little bit more about me outside of my major, your in the right place! Below I have added some of the things that make me who I am. Enjoy!

** add another photo of me that is more personal 

## My Hometown 

- Manhattan beach, ca 
- Description of where it is + its important 

## My Family 
- Photos of my family labeled who's who !
- description of the importance my family has to me 
- Favorite family activities: playing cards !

### The Family Password: Pepper
- who shes is 
- importance (ie. topic of my college essay)

## My Favorite Hobbies/Passtimes 
- surfing (include photos of me surfing)
- cooking/baking (include photos of my meals + my famous banana bread)
- yoga (map of some of my favorite studios and classes in sb)

## Education + Aspirations 
I currently have a focus in Marine Biology and Terrestrial ecology. Some of my career interests are field work and getting involved in marine or terrestrial conservation and restoration work. I am very passionate about sustainability and protecting our natural resources and species 

Some upcoming exciting news is that I will be participating in the **Bren Fellowship Program** this upcoming summer assisting on the “Promoting Wildfire Resilience in Santa Barbara County” project.  I was also selected to be published in the 2026 Edition of *Starting Lines*, the text book for the UCSB writing program. 




