---
title: "Projects"
---

**Blog post format**

ENVS 40 written project (article) 

As a class project, I wrote a long-form journal article analyzing the environmental and socioeconomic effects of on-reef construction in French Polynesia prior to the Paris 2024 Olympics. 

Skills: writing + interdisciplinary research 

WRIT 2: genre Translation document that was published in the 2026 edition of starting lines 

For a class project, I translate a peer reviewed scientific article into a podcast and a childrens book. 

Skills: science communication, writing 

WRIT 105S written project (article) 

For a class final, I wrote a long-form article assessing the importance of farmers markets in Santa Barbara, and how I use it as a form of grocery shopping, and how this helps move toward a sustainable future. 

Skills: writing 

Australia Clam Research Project (heron island) 

Went through the entire research process, where in groups we developed a research question and project outline studying Giant Clam ecology in Heron Island. Our group analyzed the differences in size and abundance across a disturbed (near by the island harbor) and undisturbed site. 

Skills: field work, research

Heal the Bay Photo Shoot Production 

Lead the production of a photoshoot to reboot the non-profit heal the bay merch website. 
Alongside professional photographer
https://shop.healthebay.org/collections/apparel 

Skills: project organization + management 

